{% set version = "0.11.0" %}

package:
  name: spyndex
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/spyndex/spyndex-{{ version }}.tar.gz
  sha256: 0c46511905ccbf5b5687b32f9555f26c57ec9bf47e8c18a116cbd9f25923e031

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - wheel
    - pip
  run:
    - python >=3.8
    - dask-core >=2023.7.0
    - matplotlib-base
    - pandas >=2.0.3
    - pyarrow
    - python-box >=6.0
    - requests
    - seaborn
    - xarray >=2023.6.0

test:
  imports:
    - spyndex
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://github.com/awesome-spectral-indices/spyndex
  summary: Awesome Spectral Indices in Python
  license: MIT
  license_file: LICENSE
  doc_url: https://spyndex.readthedocs.io/
  dev_url: https://github.com//awesome-spectral-indices/spyndex

extra:
  recipe-maintainers:
    - davemlz
